from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from yacs.config import CfgNode as CN

__C = CN()

cfg = __C

__C.DATASET = CN()
__C.DATASET.NAME = 'bengali_kaggle'
__C.DATASET.DEFAULT_SIZE = (137, 236)
__C.DATASET.RESIZE_SHAPE = (128, 128)
__C.DATASET.CONCENTRATE_CROP = True
__C.DATASET.GRAPHEME_SIZE = 168
__C.DATASET.VOWEL_SIZE = 11
__C.DATASET.CONSONANT_SIZE = 7
__C.DATASET.TRAIN_DATA_PATH = ''
__C.DATASET.VAL_DATA_PATH = ''
__C.DATASET.LABELS_WEIGHTS_PATH = ''

__C.DATASET.AUGMENTATION = CN()
__C.DATASET.AUGMENTATION.BLURRING_PROB = 0.25
__C.DATASET.AUGMENTATION.GAUSS_NOISE_PROB = 0.25
__C.DATASET.AUGMENTATION.BRIGHTNESS_CONTRAST_PROB = 1
__C.DATASET.AUGMENTATION.GRID_DISTORTION_PROB = 1
__C.DATASET.AUGMENTATION.ROTATION_PROB = 1
__C.DATASET.AUGMENTATION.ROTATION_DEGREE = 20

__C.DATASET.BATCH_SIZE = 32
__C.DATASET.CPU_NUM = 4
__C.DATASET.TO_RGB = True
__C.DATASET.NORMALIZE_MEAN = [0.485, 0.456, 0.406]
__C.DATASET.NORMALIZE_STD = [0.229, 0.224, 0.225]

__C.MODEL = CN()
__C.MODEL.NORMALIZATION_FN = 'BN'

__C.MODEL.BACKBONE = CN()
__C.MODEL.BACKBONE.TYPE = 'MOBILENET'
