DESCRIPTION: default config
DATASET:
  NAME: bengali_kaggle
  TRAIN_DATA_PATH: C:/Users/mingy/Documents/ml_data/bengali/train_data.p
  VAL_DATA_PATH: C:/Users/mingy/Documents/ml_data/bengali/val_data.p
  DEFAULT_SIZE:
  - 137
  - 236
  GRAPHEME_SIZE: 168
  VOWEL_SIZE: 11
  CONSONANT_SIZE: 7
  AUGMENTATION:
    BLURRING_PROB: 0.25
    BRIGHTNESS_CONTRAST_PROB: 1
    GAUSS_NOISE_PROB: 0.25
    GRID_DISTORTION_PROB: 1
    ROTATION_DEGREE: 20
    ROTATION_PROB: 1
  CONCENTRATE_CROP: true
  BATCH_SIZE: 32
  CPU_NUM: 4
  NORMALIZE_MEAN:
  - 0.485
  - 0.456
  - 0.406
  NORMALIZE_STD:
  - 0.229
  - 0.224
  - 0.225
  TO_RGB: true
  RESIZE_SHAPE:
  - 128
  - 128
  FOCUS_CLASS: []
MODEL:
  META_ARCHITECTURE: baseline
  NORMALIZATION_FN: BN
  BACKBONE:
    NAME: mobilenet_v2
    PRETRAINED_PATH: C:\Users\mingy\Documents\ml_data\torchvision_models\mobilenet_v2-b0353104.pth
    RGB: true
  HEAD:
    NAME: simple_head
    ACTIVATION: leaky_relu
    BN: true
    DROPOUT: -1
    HIDDEN_DIMS:
    - 512
    - 256
    INPUT_DIM: 1280
    OUTPUT_DIMS:
    - 168
    - 11
    - 7
  SOLVER:
    TOTAL_EPOCHS: 40
    OPTIMIZER: adam
    BASE_LR: 0.001
    AMP: false
    LOSS:
      LABELS_WEIGHTS_PATH: C:/Users/mingy/Documents/ml_data/bengali/labels_weights.p
      NAME: xentropy
      OHEM_RATE: 1.0
OUTPUT_PATH: ''
RESUME_PATH: ''