DATASET:
  NAME: bengali_kaggle
  TRAIN_DATA_PATH: C:/Users/mingy/Documents/ml_data/bengali/train_data.p
  VAL_DATA_PATH: C:/Users/mingy/Documents/ml_data/bengali/val_data.p
  TRAIN_DATA_SAMPLE: C:/Users/nasty/data-science/kaggle/bengali/data/interim/train_data_sample.p
  VALID_DATA_SAMPLE: C:/Users/nasty/data-science/kaggle/bengali/data/interim/valid_data_sample.p
  DEFAULT_SIZE:
  - 137
  - 236
  CONCENTRATE_CROP: true
  GRAPHEME_SIZE: 168
  VOWEL_SIZE: 11
  CONSONANT_SIZE: 7
  AUGMENTATION:
    BLURRING_PROB: 0.25
    BRIGHTNESS_CONTRAST_PROB: 1
    GAUSS_NOISE_PROB: 0.25
    GRID_DISTORTION_PROB: 1
    ROTATION_DEGREE: 20
    ROTATION_PROB: 1
    CUTOUT_PROB: 0.3
    HEIGHT: 128
    WIDTH: 128
  BATCH_SIZE: 32
  CPU_NUM: 1
  NORMALIZE_MEAN:
  - 0.485
  - 0.456
  - 0.406
  NORMALIZE_STD:
  - 0.229
  - 0.224
  - 0.225
  TO_RGB: true
  RESIZE_SHAPE:
  - 128
  - 128
MODEL:
  META_ARCHITECTURE: baseline
  NORMALIZATION_FN: BN
  BACKBONE:
    NAME: mobilenet_v2
    PRETRAINED_PATH: C:/Users/nasty/data-science/kaggle/bengali/bengali-julien/models/mobilenet_v2-b0353104.pth
  HEAD:
    NAME: simple_head
    ACTIVATION: leaky_relu
    BN: true
    DROPOUT: -1
    HIDDEN_DIMS:
    - 512
    - 256
    INPUT_DIM: 1280
    OUTPUT_DIMS:
    - 168
    - 11
    - 7
  SOLVER:
    LABELS_WEIGHTS_PATH: C:/Users/nasty/data-science/kaggle/bengali/data/interim/labels_weights.p
    OHEM_RATE: 1
    MIXUP_AUGMENT: true
    MIXUP:
      CUTMIX_ALPHA: 1
      MIXUP_ALPHA: 0.4
      CUTMIX_PROB: 0.4
    OPTIMIZER:
      OPTIMIZER: adam
      BASE_LR: 0.001
    SCHEDULER:
      NAME: OneCycleLR
      TOTAL_EPOCHS: 40
      MAX_LR: 0.01
    LOSS:
      NAME: xentropy
      OHEM_RATE: 1.0

OUTPUT_PATH: ''
RESUME_PATH: ''