DATASET:
    BATCH_SIZE: 256
    AUGMENTATION:
        BRIGHTNESS_CONTRAST_PROB: 1.0
        GRID_DISTORTION_PROB: 1.0
        ROTATION_PROB: 1.0
MODEL: 
  BACKBONE:
    NAME: se_resnext50
    PRETRAINED_PATH: /home/jupyter/kaggle-computer-vision-competition/models/se_resnext50_32x4d-a260b3a4.pth
  HEAD:
    INPUT_DIM: 2048
  SOLVER: 
    LOSS:
      NAME: label_smoothing_ce
    SCHEDULER:
      TOTAL_EPOCHS: 80
RESUME_PATH: /home/jupyter/kaggle-computer-vision-competition/experiments/exp13/model_backups/model_bak_000034.pt


