DATASET:
    RESIZE_SHAPE: (224,224)
    BATCH_SIZE: 64
MODEL: 
  BACKBONE:
    NAME: densenet121
    PRETRAINED_PATH: /home/jupyter/kaggle-computer-vision-competition/models/densenet121.pth
  HEAD:
    INPUT_DIM: 1000
  SOLVER: 
    LOSS:
      OHEM_RATE: 0.7
    SCHEDULER:
      TOTAL_EPOCHS: 80
RESUME_PATH: /home/jupyter/kaggle-computer-vision-competition/experiments/exp10/model_backups/model_bak_000068.pt

